---
title: "EconRe Experiment"
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: "Joona Lohtander"
bibliography: library.bib
link-citations: true
output: 
    html_document:
        includes:
            in_header: meta.html
---

## Take part in an experiment and earn!

The experiment takes approximately 60 minutes in total. All participants are paid
a show up fee of 10 € and a bonus of up to 7.7 € depending on choices made during
the experiment.

To participate, follow the steps below.

For questions, please don't hesitate to contact me at [joona.lohtander@oulu.fi](mailto:joona.lohtander@oulu.fi).

### 1. Join the UbiComp Sona Systems participant pool (optional)

For a smooth registration, you can join the UbiComp Sona Systems participant pool here: [Sona Systems](https://oulu-ubicomp.sona-systems.com)

Just click on 'Request Account' and fill all the info. If you wish to only take part
in this experiment and do not wish to register to the participant pool, please contact
me directly.

### 2. Find a suitable session time

You can find the session times from Sona Systems after registration and book
your session time directly from there. Otherwise, you may contact me
directly.

All sessions are in the computer room TA102 in Linnanmaa Campus. The preliminary
session times are:

Wednesday 27.5. at 10, 12 and 14
Thursday 28.5. at 12 and 14
Tuesday 2.6. at 10, 12 and 14
Thursday 4.6. at 10, 12 and 14

More sessions will be scheduled depending on participation numbers!

### 4. Show up

You do not need to do any preparation before the experiment. For smooth payment,
we ask you to set up MobilePay. If you are unable to do that, please make sure
you have your account details ready.

